sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  - LIBRARY=eCP DATASET=random-xs-20-angular

before_install:
  - pip install -r requirements.txt
  - python install.py

script:
  - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --timeout 300
  - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --batch --timeout 300
  - sudo chmod -R 777 results/
  - python plot.py --dataset $DATASET --output plot.png
  - python plot.py --dataset $DATASET --output plot-batch.png --batch
  - python -m unittest test/test-metrics.py
  - python -m unittest test/test-jaccard.py
  - python create_website.py --outputdir . --scatter --latex
